### ISSUE TITLE
setValue should consider 0 a valid value and pass this through

### ISSUE THREAD

**Issue by conspicuus** [pubfood/pubfood#37]
Currently, a bid value of 0 will be changed to an empty string in the setValue method:

```Bid.prototype.setValue = function(v) {
  this.value = v || '';
  this.type = util.asType(this.value);
  return this;
};```

0 should be passed as a valid value.

Specifically, setting targeting on a bid for a slot of 'key': 0 should be passed to DFP as key=0, not key=

**Comment by elljoh** [comment]
[Bid.setValue()](src/model/bid.js#L60) should allow at least a numeric zero to be set to the bid `value`. I think just setting the value as passed in is appropriate.

I think that if a targeting key is being set to zero, but is not being passed as a zero value in the DFP request; this is probably a similar problem but at the time of building the targeting values for the ad server request.

When a bid provider calls `pushBid` an object is passed to pubfood and internally `var bid = Bid.fromObject(bidObject);` is called to construct the Bid object.

If for example the bid object is `{value: 0, targeting: { zero: 0 }}`, the the respective Bid object values should indeed be numeric zero.

This indicates that there may be an issue, similar or otherwise, with the ad server targeting request build.

We can resolve both issues as part of this bug.
